apiVersion: v1
kind: Service
metadata:
  name: petclinic-service
  labels:
    name: petclinic-service
    app: demo-petclinic-app
spec:
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 9090
  selector:
    name: petclinic-app-pod
    app: demo-petclinic-app